### ISSUE TITLE
`TypeError: feature.plugin is not a function`

### ISSUE THREAD

**Issue by mikestopcontinues** [postcss/postcss-easings#12]
Hey, I was using this plugin successfully within `postcss-preset-env` for a while, but I just spun it up recently, and it seems there's a compatibility issue. Is it possible the plugin API has changed with recent updates?

Sample broken config:
```
module.exports = {
  plugins: [
    [
      'postcss-preset-env', { // NOTE: Using string syntax rather than require on this line for NextJS.
        insertAfter: {
          'all-property': [
            require('postcss-easings')(),
          ],
        },
      },
    ],
  ],
};
```

**Comment by ai** [comment]
Can you try:

```js
module.exports = {
  plugins: [
    'postcss-preset-env',
    'postcss-easings'
  ],
};
```

And double-check that you are using PostCSS 8.

**Comment by mikestopcontinues** [comment]
Ahh, there it is. I thought it was using my postcss dep (8.1.1), but Next runs 7.0.X. I see you have [an issue](https://github.com/vercel/next.js/issues/17242) already. Seems like that's the real cause.

In the meantime it looks like v2 is the right version for me?

**Comment by ai** [comment]
Yeap 2.x will work with PostCSS 7.x

**Comment by mikestopcontinues** [comment]
Thanks for your help! I guess it's safe to call this closed.
