### ISSUE TITLE
Why use

### ISSUE THREAD

**Issue by custa1200** [postcss/postcss-easings#2]
Hi I am wanting to understand the benefits of using this plugin. Looking at what the code changes from and to, the byte count would be increased, does it somehow Gzip better to the client?

**Comment by ai** [comment]
@custa1200 this plugin is not for size compression, but for writing readable code.

Browsers support only `cubic-bezier()` time functions. So you can’t write just `ease-in-sine`.

This plugin will add human-readable time functions names like `ease-in-sine`.
