### ISSUE TITLE
CSS variable support

### ISSUE THREAD

**Issue by silasabbott** [postcss/postcss-easings#26]
It seems like any easings defined in a CSS variable are not transformed. CSS variables are [well supported](https://caniuse.com/css-variables) now—any way we can add support for them?

**Comment by ai** [comment]
Sure, I will try to add support tomorrow

**Comment by ai** [comment]
Plugin already works with Custom Properties f00f523

What problems do you have?

**Comment by silasabbott** [comment]
Shoot, that was completely my mistake. Another tool I use takes `cubicInOut` instead of `easeInOutCubic` and I got them mixed up. Sorry for the inconvenience—appreciate the help!
